services:
  - type: web
    name: beyondchats-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: SESSION_DRIVER
        value: array
      - key: CACHE_DRIVER
        value: array
